name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload website files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # ✅ FIX IS HERE

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Show Dashboard Link
        run: |
          echo "## 🚀 Deployment Successful" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔗 Open Dashboard" >> $GITHUB_STEP_SUMMARY
          echo "[Click Here](https://saikrishnakalle.github.io/program2/)" >> $GITHUB_STEP_SUMMARY
